# Generated by Django 6.0.2 on 2026-06-23 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0012_alter_trasladorecurso_ambiente_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladorecurso',
            name='estado',
            field=models.CharField(default='Prestado', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertasinasistencia',
            name='aprendiz_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alertasinasistencia',
            name='cantidad_fallas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alertasinasistencia',
            name='fecha_alerta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alertasinasistencia',
            name='id_alerta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alertasinasistencia',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='capacidad',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='estado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='id_ambiente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='num_ambiente',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='tipo_ambiente',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='coordinacion',
            name='correo_coordinacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinacion',
            name='id_coordinacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coordinacion',
            name='nombre_coordinacion',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='historicoincidentes',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicoincidentes',
            name='fecha_registro',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicoincidentes',
            name='id_historico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='id_jornada',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='nombre_jornada',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='id_modalidad',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='nombre_modalidad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='programas',
            name='duracion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='id_programas',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programas',
            name='nivel_formacion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='programas',
            name='nombre_programa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='estado',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='id_recurso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='nombre_recurso',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='num_recurso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='serial_recurso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrominuta',
            name='descripcion_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrominuta',
            name='estado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registrominuta',
            name='fecha_hora_entrega',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registrominuta',
            name='fecha_hora_recibo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registrominuta',
            name='id_minuta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrominuta',
            name='novedad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='tipoincidente',
            name='id_tipo_inc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoincidente',
            name='observacion_inc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tipoincidente',
            name='tipo_incidente',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='tiporecurso',
            name='descripcion_tipo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tiporecurso',
            name='id_tipo_recurso',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiporecurso',
            name='recurso_tipo',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='ambiente_destino',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='ambiente_origen',
            field=models.ForeignKey(db_column='ambiente_origen', on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.ambiente'),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='fecha_traslado',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.recursos'),
        ),
    ]
